import urllib.request
import json

API_KEY = "314c7e9d7ba045308e8f73c0bb9136b4"
HOST = "www.backyardstudioofficial.com"
KEY_LOCATION = f"https://{HOST}/{API_KEY}.txt"

URLS = [
    # English pages
    f"https://{HOST}/",
    f"https://{HOST}/about",
    f"https://{HOST}/services",
    f"https://{HOST}/pricing",
    f"https://{HOST}/contact",
    f"https://{HOST}/blog",
    f"https://{HOST}/testimonials",
    f"https://{HOST}/locations",
    f"https://{HOST}/portfolio",
    # Wedding landing pages (Tier 1+2, 2026-06-10)
    f"https://{HOST}/services/wedding-photography",
    f"https://{HOST}/services/wedding-videography",
    f"https://{HOST}/services/pre-wedding-shoot",
    f"https://{HOST}/wedding-packages",
    f"https://{HOST}/services/affordable-wedding-photography",
    f"https://{HOST}/services/flying-dress-photoshoot",
    f"https://{HOST}/services/wedding-photography-abu-dhabi",
    # Wedding indexing build (2026-06-12)
    f"https://{HOST}/weddings",
    f"https://{HOST}/services/wedding-photography-sharjah",
    f"https://{HOST}/services/wedding-photography-ajman",
    f"https://{HOST}/services/wedding-photography-ras-al-khaimah",
    f"https://{HOST}/services/wedding-photography-fujairah",
    f"https://{HOST}/services/wedding-photography-umm-al-quwain",
    # English locations
    f"https://{HOST}/locations/dubai",
    f"https://{HOST}/locations/abu-dhabi",
    f"https://{HOST}/locations/sharjah",
    f"https://{HOST}/locations/ajman",
    f"https://{HOST}/locations/ras-al-khaimah",
    f"https://{HOST}/locations/fujairah",
    f"https://{HOST}/locations/umm-al-quwain",
    # Arabic pages
    f"https://{HOST}/ar/",
    f"https://{HOST}/ar/about",
    f"https://{HOST}/ar/services",
    f"https://{HOST}/ar/pricing",
    f"https://{HOST}/ar/contact",
    f"https://{HOST}/ar/blog",
    f"https://{HOST}/ar/testimonials",
    f"https://{HOST}/ar/locations",
    # Chinese pages
    f"https://{HOST}/zh/",
    f"https://{HOST}/zh/about",
    f"https://{HOST}/zh/services",
    f"https://{HOST}/zh/pricing",
    f"https://{HOST}/zh/contact",
    f"https://{HOST}/zh/blog",
    f"https://{HOST}/zh/testimonials",
    f"https://{HOST}/zh/locations",
    # Russian pages
    f"https://{HOST}/ru/",
    f"https://{HOST}/ru/about",
    f"https://{HOST}/ru/services",
    f"https://{HOST}/ru/pricing",
    f"https://{HOST}/ru/contact",
    f"https://{HOST}/ru/blog",
    f"https://{HOST}/ru/testimonials",
    f"https://{HOST}/ru/locations",
    # EN Blog posts — Batch 1
    f"https://{HOST}/blog/best-production-companies-dubai-2026",
    f"https://{HOST}/blog/how-much-does-video-production-cost-dubai-2026",
    f"https://{HOST}/blog/wedding-photographer-cost-dubai-2026",
    f"https://{HOST}/blog/drone-photography-dubai-2026",
    f"https://{HOST}/blog/real-estate-videography-dubai-2026",
    f"https://{HOST}/blog/brand-film-production-dubai-2026",
    f"https://{HOST}/blog/social-media-content-creation-dubai-2026",
    f"https://{HOST}/blog/corporate-photography-dubai-2026",
    f"https://{HOST}/blog/automotive-photography-dubai-2026",
    f"https://{HOST}/blog/hotel-photography-dubai-2026",
    f"https://{HOST}/blog/product-photography-dubai-2026",
    f"https://{HOST}/blog/youtube-video-production-dubai-2026",
    f"https://{HOST}/blog/fashion-photography-dubai-2026",
    # EN Blog posts — Batch 2
    f"https://{HOST}/blog/event-photography-dubai-2026",
    f"https://{HOST}/blog/food-photography-dubai-2026",
    f"https://{HOST}/blog/real-estate-photography-dubai-2026",
    f"https://{HOST}/blog/corporate-video-production-dubai-2026",
    f"https://{HOST}/blog/music-video-production-dubai-2026",
    f"https://{HOST}/blog/company-profile-video-dubai-2026",
    f"https://{HOST}/blog/testimonial-video-dubai-2026",
    f"https://{HOST}/blog/influencer-content-creator-dubai-2026",
    f"https://{HOST}/blog/downtown-dubai-photographer-2026",
    f"https://{HOST}/blog/restaurant-photography-dubai-2026",
    f"https://{HOST}/blog/luxury-lifestyle-photography-dubai-2026",
    f"https://{HOST}/blog/birthday-party-photographer-dubai-2026",
    f"https://{HOST}/blog/abu-dhabi-photographer-2026",
    f"https://{HOST}/blog/filipino-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/sports-photography-dubai-2026",
    f"https://{HOST}/blog/green-screen-studio-dubai-2026",
    # Sub-industry pages (all 23 sub-slugs)
    f"https://{HOST}/industries/automotive/dealership",
    f"https://{HOST}/industries/hospitality/resorts",
    f"https://{HOST}/industries/real-estate/luxury-villa",
    f"https://{HOST}/industries/real-estate/off-plan",
    f"https://{HOST}/industries/fashion/model-portfolio",
    f"https://{HOST}/industries/fashion/fashion-reels",
    f"https://{HOST}/industries/food-beverage/restaurants",
    f"https://{HOST}/industries/food-beverage/menu-photography",
    f"https://{HOST}/industries/sports/football",
    f"https://{HOST}/industries/sports/fitness",
    f"https://{HOST}/industries/corporate/investor-pitch",
    f"https://{HOST}/industries/corporate/annual-report",
    f"https://{HOST}/industries/tech/saas",
    f"https://{HOST}/industries/sports/padel",
    f"https://{HOST}/industries/automotive/car-launch",
    f"https://{HOST}/industries/sports/cycling",
    f"https://{HOST}/industries/sports/running",
    f"https://{HOST}/industries/tech/gitex",
    f"https://{HOST}/industries/tech/startup",
    f"https://{HOST}/industries/tech/fintech",
    f"https://{HOST}/industries/healthcare/dental",
    f"https://{HOST}/industries/corporate/company-profile",
    f"https://{HOST}/industries/hospitality/hotels",
    # EN Blog posts — Batch 3 (photography guides)
    f"https://{HOST}/blog/ecommerce-product-photography-dubai-2026",
    f"https://{HOST}/blog/aerial-videography-dubai-2026",
    f"https://{HOST}/blog/family-photographer-dubai-2026",
    f"https://{HOST}/blog/passport-photo-dubai-2026",
    f"https://{HOST}/blog/corporate-event-videography-dubai-2026",
    f"https://{HOST}/blog/newborn-photographer-dubai-2026",
    f"https://{HOST}/blog/maternity-photographer-dubai-2026",
    f"https://{HOST}/blog/brand-photography-dubai-2026",
    f"https://{HOST}/blog/360-video-production-dubai-2026",
    f"https://{HOST}/blog/graduation-photographer-dubai-2026",
    # RU Blog posts
    f"https://{HOST}/ru/blog/korporativnoe-video-dubai-2026",
    f"https://{HOST}/ru/blog/semka-nedvizhimosti-dubai-2026",
    f"https://{HOST}/ru/blog/svadebnyi-fotograf-dubai-2026",
    f"https://{HOST}/ru/blog/stoimost-videosemki-dubai-2026",
    f"https://{HOST}/ru/blog/rily-socsietey-dubai-2026",
    f"https://{HOST}/ru/blog/fotosyomka-feropriiatiy-dubai-2026",
    f"https://{HOST}/ru/blog/fotografiya-edy-dubai-2026",
    f"https://{HOST}/ru/blog/semeinaya-fotosessiya-dubai-2026",
    f"https://{HOST}/ru/blog/fotograf-novorozhdennykh-dubai-2026",
    # AR Blog posts
    f"https://{HOST}/ar/blog/video-sharikaat-dubai-2026",
    f"https://{HOST}/ar/blog/taswiremolak-dubai-2026",
    f"https://{HOST}/ar/blog/taswirzifaf-dubai-2026",
    f"https://{HOST}/ar/blog/asear-tasswirvideo-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-zifaf-emirati-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-zifaf-arabi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-taaam-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-muatamart-dubai-2026",
    f"https://{HOST}/ar/blog/tasjil-video-faaliyat-dubai-2026",
    f"https://{HOST}/ar/blog/intaj-klip-musiqi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-khetuba-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-mawaalid-dubai-2026",
    # EN Blog posts — Batch 4 (keyword gap fills, 2026-06-17)
    f"https://{HOST}/blog/portrait-photographer-dubai-2026",
    f"https://{HOST}/blog/reels-videographer-dubai-2026",
    f"https://{HOST}/blog/personal-branding-photographer-dubai-2026",
    f"https://{HOST}/blog/amazon-product-photography-dubai-2026",
    f"https://{HOST}/blog/headshot-photographer-dubai-2026",
    # EN Blog posts — Tier 2 gap fills (2026-06-18)
    f"https://{HOST}/blog/freelance-photographer-dubai-2026",
    f"https://{HOST}/blog/watch-photography-dubai-2026",
    f"https://{HOST}/blog/men-photographer-dubai-2026",
    # EN Blog posts — Sprint 1: Wedding sub-niches (2026-06-18)
    f"https://{HOST}/blog/indian-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/pakistani-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/emirati-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/filipino-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/pre-wedding-shoot-dubai-2026",
    f"https://{HOST}/blog/nigerian-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/russian-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/luxury-wedding-photographer-dubai-2026",
    # EN Blog posts — Sprint 2: Sports sub-niches (2026-06-18)
    f"https://{HOST}/blog/cricket-photographer-dubai-2026",
    f"https://{HOST}/blog/football-photographer-dubai-2026",
    f"https://{HOST}/blog/tennis-photographer-dubai-2026",
    f"https://{HOST}/blog/golf-photographer-dubai-2026",
    f"https://{HOST}/blog/fitness-photographer-dubai-2026",
    f"https://{HOST}/blog/gym-photography-dubai-2026",
    f"https://{HOST}/blog/marathon-photographer-dubai-2026",
    f"https://{HOST}/blog/motorsport-photographer-dubai-2026",
    # EN Blog posts — Sprint 3: Lifestyle & portrait sub-niches (2026-06-18)
    f"https://{HOST}/blog/couple-photoshoot-dubai-2026",
    f"https://{HOST}/blog/kids-photographer-dubai-2026",
    f"https://{HOST}/blog/baby-photographer-dubai-2026",
    f"https://{HOST}/blog/pregnancy-photoshoot-dubai-2026",
    f"https://{HOST}/blog/desert-photoshoot-dubai-2026",
    f"https://{HOST}/blog/social-media-photographer-dubai-2026",
    f"https://{HOST}/blog/engagement-photographer-dubai-2026",
    # EN Blog posts — Sprint 4: Commercial sub-niches (2026-06-18)
    f"https://{HOST}/blog/jewellery-photography-dubai-2026",
    f"https://{HOST}/blog/car-photography-dubai-2026",
    f"https://{HOST}/blog/interior-photography-dubai-2026",
    f"https://{HOST}/blog/perfume-photography-dubai-2026",
    f"https://{HOST}/blog/cosmetics-photography-dubai-2026",
    # EN Blog posts — Sprint 5: Video sub-niches (2026-06-18)
    f"https://{HOST}/blog/wedding-videographer-dubai-2026",
    f"https://{HOST}/blog/instagram-reels-videographer-dubai-2026",
    f"https://{HOST}/blog/tiktok-videographer-dubai-2026",
    # RU Blog posts — Sprint 5 (2026-06-18)
    f"https://{HOST}/ru/blog/svadebnyi-fotograf-indiyskaya-svadba-dubai-2026",
    f"https://{HOST}/ru/blog/detskiy-fotograf-dubai-2026",
    f"https://{HOST}/ru/blog/sportivnyi-fotograf-dubai-2026",
    f"https://{HOST}/ru/blog/fotosessiya-beremennosti-dubai-2026",
    f"https://{HOST}/ru/blog/predsvadebnaya-fotosessiya-dubai-2026",
    f"https://{HOST}/ru/blog/fotograf-para-dubai-2026",
    # AR Blog posts — Sprint 5 (2026-06-18)
    f"https://{HOST}/ar/blog/taswir-aris-hindi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-atfal-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-riyadi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-intaj-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-nisa-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-aqariya-dubai-2026",
    # EN Blog posts — Sprint 6: Tier 1 high-demand keywords (2026-06-18)
    f"https://{HOST}/blog/motion-graphics-dubai-2026",
    f"https://{HOST}/blog/live-streaming-dubai-2026",
    f"https://{HOST}/blog/3d-animation-dubai-2026",
    f"https://{HOST}/blog/video-editing-dubai-2026",
    f"https://{HOST}/blog/studio-rental-dubai-2026",
    f"https://{HOST}/blog/2d-animation-dubai-2026",
    f"https://{HOST}/blog/post-production-dubai-2026",
    # EN Blog posts — Sprint 7: Tier 2 video service pages (2026-06-18)
    f"https://{HOST}/blog/timelapse-video-dubai-2026",
    f"https://{HOST}/blog/voice-over-artist-dubai-2026",
    f"https://{HOST}/blog/arabic-voice-over-dubai-2026",
    f"https://{HOST}/blog/tv-commercial-dubai-2026",
    f"https://{HOST}/blog/commercial-production-dubai-2026",
    f"https://{HOST}/blog/conference-video-dubai-2026",
    f"https://{HOST}/blog/event-videographer-dubai-2026",
    f"https://{HOST}/blog/explainer-video-dubai-2026",
    # Case study pages — Sprint 9 (2026-06-19)
    f"https://{HOST}/case-studies",
    f"https://{HOST}/case-studies/real-estate-video-campaign-dubai",
    f"https://{HOST}/case-studies/social-media-content-production-dubai",
    f"https://{HOST}/case-studies/corporate-event-video-production-dubai",
    f"https://{HOST}/case-studies/hotel-brand-film-dubai",
    f"https://{HOST}/case-studies/fashion-campaign-production-dubai",
    # EN Blog posts — Sprint 10: wedding sub-niches + commercial photography (2026-06-19)
    f"https://{HOST}/blog/indian-wedding-photography-dubai-2026",
    f"https://{HOST}/blog/arabic-wedding-photography-dubai-2026",
    f"https://{HOST}/blog/destination-wedding-dubai-2026",
    f"https://{HOST}/blog/nikah-photography-dubai-2026",
    f"https://{HOST}/blog/personal-branding-photography-dubai-2026",
    f"https://{HOST}/blog/food-photography-dubai-2026",
    f"https://{HOST}/blog/product-photography-dubai-2026",
    f"https://{HOST}/blog/lifestyle-photography-dubai-2026",
    # Blog category hub pages (2026-06-19)
    f"https://{HOST}/blog/category/wedding",
    f"https://{HOST}/blog/category/video",
    f"https://{HOST}/blog/category/photography",
    f"https://{HOST}/blog/category/social-media",
    f"https://{HOST}/blog/category/industry",
    # RU Blog posts — missing from earlier batches (2026-06-19)
    f"https://{HOST}/ru/blog/svadebnyi-fotograf-abu-dhabi-2026",
    f"https://{HOST}/ru/blog/fotografiya-nedvizhimosti-dubai-2026",
    # Sprint 10 AR translations (2026-06-19)
    f"https://{HOST}/ar/blog/taswir-zifaf-hindi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-afraah-arabiya-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-zifaf-wajiha-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-nikah-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-brand-shakhsi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-mataam-ihtirafi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-muntajat-tijaria-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-uslub-hayat-dubai-2026",
    # Sprint 12: Dubai location sub-pages (2026-06-22)
    f"https://{HOST}/locations/dubai/wedding-photography",
    f"https://{HOST}/locations/dubai/corporate-video",
    f"https://{HOST}/locations/dubai/event-photography",
    f"https://{HOST}/locations/dubai/real-estate-photography",
    f"https://{HOST}/locations/dubai/drone-videography",
    f"https://{HOST}/locations/dubai/food-photography",
    f"https://{HOST}/locations/dubai/product-photography",
    f"https://{HOST}/locations/dubai/personal-branding-photography",
    # Sprint 11: Abu Dhabi location sub-pages (2026-06-22)
    f"https://{HOST}/locations/abu-dhabi/wedding-photography",
    f"https://{HOST}/locations/abu-dhabi/corporate-video",
    f"https://{HOST}/locations/abu-dhabi/event-photography",
    f"https://{HOST}/locations/abu-dhabi/real-estate-photography",
    f"https://{HOST}/locations/abu-dhabi/drone-videography",
    f"https://{HOST}/locations/abu-dhabi/food-photography",
    f"https://{HOST}/locations/abu-dhabi/product-photography",
    f"https://{HOST}/locations/abu-dhabi/personal-branding-photography",
    # Sprint 10 RU translations (2026-06-19)
    f"https://{HOST}/ru/blog/indiyskaya-svadba-fotografiya-dubai-2026",
    f"https://{HOST}/ru/blog/arabskaya-svadba-fotografiya-dubai-2026",
    f"https://{HOST}/ru/blog/vyezdnaya-svadba-dubai-2026",
    f"https://{HOST}/ru/blog/nikah-fotografiya-dubai-2026",
    f"https://{HOST}/ru/blog/personal-brending-fotografiya-dubai-2026",
    f"https://{HOST}/ru/blog/fotografiya-restoranov-dubai-2026",
    f"https://{HOST}/ru/blog/fotografiya-tovarov-dubai-2026",
    f"https://{HOST}/ru/blog/layfstayl-fotografiya-dubai-2026",
    # Sprint 13: EN blog posts — remaining Dubai niches (2026-06-22)
    f"https://{HOST}/blog/headshot-photography-dubai-2026",
    f"https://{HOST}/blog/newborn-photographer-dubai-2026",
    f"https://{HOST}/blog/maternity-photography-dubai-2026",
    f"https://{HOST}/blog/fashion-photography-dubai-2026",
    f"https://{HOST}/blog/social-media-content-creator-dubai-2026",
    f"https://{HOST}/blog/birthday-photographer-dubai-2026",
    f"https://{HOST}/blog/kids-photography-dubai-2026",
    f"https://{HOST}/blog/engagement-photographer-dubai-2026",
    # Sprint 13: Dubai location sub-pages (2026-06-22)
    f"https://{HOST}/locations/dubai/headshot-photography",
    f"https://{HOST}/locations/dubai/newborn-photography",
    f"https://{HOST}/locations/dubai/maternity-photography",
    f"https://{HOST}/locations/dubai/fashion-photography",
    f"https://{HOST}/locations/dubai/social-media-content",
    f"https://{HOST}/locations/dubai/birthday-photography",
    f"https://{HOST}/locations/dubai/kids-photography",
    f"https://{HOST}/locations/dubai/engagement-photography",
    # Sprint 14: Abu Dhabi location sub-pages — new niches (2026-06-22)
    f"https://{HOST}/locations/abu-dhabi/headshot-photography",
    f"https://{HOST}/locations/abu-dhabi/newborn-photography",
    f"https://{HOST}/locations/abu-dhabi/maternity-photography",
    f"https://{HOST}/locations/abu-dhabi/fashion-photography",
    f"https://{HOST}/locations/abu-dhabi/social-media-content",
    f"https://{HOST}/locations/abu-dhabi/birthday-photography",
    f"https://{HOST}/locations/abu-dhabi/kids-photography",
    f"https://{HOST}/locations/abu-dhabi/engagement-photography",
    # Multilingual media parity sprint (2026-06-22)
    # Updated pages with real images/videos — resubmit for recrawl
    f"https://{HOST}/ar/",
    f"https://{HOST}/ar/portfolio",
    f"https://{HOST}/ar/about",
    f"https://{HOST}/ar/locations",
    f"https://{HOST}/ru/",
    f"https://{HOST}/ru/portfolio",
    f"https://{HOST}/ru/about",
    f"https://{HOST}/ru/locations",
    # AR blog posts not previously submitted
    f"https://{HOST}/ar/blog/asear-video-sharkati-dubai-2026",
    f"https://{HOST}/ar/blog/taswirafidiyat-dubai-2026",
    # AR/RU blog posts updated with hero images — resubmit
    f"https://{HOST}/ar/blog/taswir-zifaf-arabi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-zifaf-hindi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-zifaf-wajiha-dubai-2026",
    f"https://{HOST}/ru/blog/arabskaya-svadba-fotografiya-dubai-2026",
    f"https://{HOST}/ru/blog/indiyskaya-svadba-fotografiya-dubai-2026",
    f"https://{HOST}/ru/blog/vyezdnaya-svadba-dubai-2026",
    f"https://{HOST}/ru/blog/nikah-fotografiya-dubai-2026",
    f"https://{HOST}/ru/blog/personal-brending-fotografiya-dubai-2026",
    f"https://{HOST}/ru/blog/fotografiya-restoranov-dubai-2026",
    f"https://{HOST}/ru/blog/fotografiya-tovarov-dubai-2026",
    f"https://{HOST}/ru/blog/layfstayl-fotografiya-dubai-2026",
    # Sprint 15 AR (2026-06-22)
    f"https://{HOST}/ar/blog/taswir-headshot-mihni-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-atfal-mawludeen-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-haml-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-moda-ihtirafiya-dubai-2026",
    f"https://{HOST}/ar/blog/sani-muhtawa-shbaka-ijtimaia-dubai-2026",
    f"https://{HOST}/ar/blog/musawir-eid-milad-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-atfal-ihtirafiya-dubai-2026",
    f"https://{HOST}/ar/blog/musawir-khetuba-ihtirafiya-dubai-2026",
    # Sprint 15 RU (2026-06-22)
    f"https://{HOST}/ru/blog/headshot-fotografiya-dubai-2026",
    f"https://{HOST}/ru/blog/fotosessiya-novorozhdennykh-dubai-2026",
    f"https://{HOST}/ru/blog/fotografiya-beremennosti-dubai-2026",
    f"https://{HOST}/ru/blog/fashion-fotografiya-dubai-2026",
    f"https://{HOST}/ru/blog/kreator-kontenta-sotssetey-dubai-2026",
    f"https://{HOST}/ru/blog/fotograf-na-den-rozhdeniya-dubai-2026",
    f"https://{HOST}/ru/blog/fotografiya-detey-dubai-2026",
    f"https://{HOST}/ru/blog/fotograf-na-pomolvku-dubai-2026",

    # Sprint 16: Sharjah location sub-pages (2026-06-22)
    f"https://{HOST}/locations/sharjah/headshot-photography",
    f"https://{HOST}/locations/sharjah/newborn-photography",
    f"https://{HOST}/locations/sharjah/maternity-photography",
    f"https://{HOST}/locations/sharjah/fashion-photography",
    f"https://{HOST}/locations/sharjah/social-media-content",
    f"https://{HOST}/locations/sharjah/birthday-photography",
    f"https://{HOST}/locations/sharjah/kids-photography",
    f"https://{HOST}/locations/sharjah/engagement-photography",
    # Sprint 17: Ajman location sub-pages (2026-06-23)
    f"https://{HOST}/locations/ajman/headshot-photography",
    f"https://{HOST}/locations/ajman/newborn-photography",
    f"https://{HOST}/locations/ajman/maternity-photography",
    f"https://{HOST}/locations/ajman/fashion-photography",
    f"https://{HOST}/locations/ajman/social-media-content",
    f"https://{HOST}/locations/ajman/birthday-photography",
    f"https://{HOST}/locations/ajman/kids-photography",
    f"https://{HOST}/locations/ajman/engagement-photography",
    # Sprint 18: Ras Al Khaimah location sub-pages (2026-06-23)
    f"https://{HOST}/locations/ras-al-khaimah/headshot-photography",
    f"https://{HOST}/locations/ras-al-khaimah/newborn-photography",
    f"https://{HOST}/locations/ras-al-khaimah/maternity-photography",
    f"https://{HOST}/locations/ras-al-khaimah/fashion-photography",
    f"https://{HOST}/locations/ras-al-khaimah/social-media-content",
    f"https://{HOST}/locations/ras-al-khaimah/birthday-photography",
    f"https://{HOST}/locations/ras-al-khaimah/kids-photography",
    f"https://{HOST}/locations/ras-al-khaimah/engagement-photography",
    # Sprint 19: Fujairah location sub-pages (2026-06-23)
    f"https://{HOST}/locations/fujairah/headshot-photography",
    f"https://{HOST}/locations/fujairah/newborn-photography",
    f"https://{HOST}/locations/fujairah/maternity-photography",
    f"https://{HOST}/locations/fujairah/fashion-photography",
    f"https://{HOST}/locations/fujairah/social-media-content",
    f"https://{HOST}/locations/fujairah/birthday-photography",
    f"https://{HOST}/locations/fujairah/kids-photography",
    f"https://{HOST}/locations/fujairah/engagement-photography",
    # Sprint 20: Umm Al Quwain location sub-pages (2026-06-23)
    f"https://{HOST}/locations/umm-al-quwain/headshot-photography",
    f"https://{HOST}/locations/umm-al-quwain/newborn-photography",
    f"https://{HOST}/locations/umm-al-quwain/maternity-photography",
    f"https://{HOST}/locations/umm-al-quwain/fashion-photography",
    f"https://{HOST}/locations/umm-al-quwain/social-media-content",
    f"https://{HOST}/locations/umm-al-quwain/birthday-photography",
    f"https://{HOST}/locations/umm-al-quwain/kids-photography",
    f"https://{HOST}/locations/umm-al-quwain/engagement-photography",
]

payload = {
    "host": HOST,
    "key": API_KEY,
    "keyLocation": KEY_LOCATION,
    "urlList": URLS,
}

req = urllib.request.Request(
    "https://api.indexnow.org/indexnow",
    data=json.dumps(payload).encode("utf-8"),
    headers={"Content-Type": "application/json; charset=utf-8"},
    method="POST",
)

with urllib.request.urlopen(req) as resp:
    print(f"Status: {resp.status}")
    print(f"URLs submitted: {len(URLS)}")
    print("Done.")
