import urllib.request
import json

API_KEY = "314c7e9d7ba045308e8f73c0bb9136b4"
HOST = "www.backyardstudioofficial.com"
KEY_LOCATION = f"https://{HOST}/{API_KEY}.txt"

URLS = [
    # English pages
    f"https://{HOST}/",
    f"https://{HOST}/about",
    f"https://{HOST}/services",
    f"https://{HOST}/pricing",
    f"https://{HOST}/contact",
    f"https://{HOST}/blog",
    f"https://{HOST}/testimonials",
    f"https://{HOST}/locations",
    f"https://{HOST}/portfolio",
    # Wedding landing pages (Tier 1+2, 2026-06-10)
    f"https://{HOST}/services/wedding-photography",
    f"https://{HOST}/services/wedding-videography",
    f"https://{HOST}/services/pre-wedding-shoot",
    f"https://{HOST}/wedding-packages",
    f"https://{HOST}/services/affordable-wedding-photography",
    f"https://{HOST}/services/flying-dress-photoshoot",
    f"https://{HOST}/services/wedding-photography-abu-dhabi",
    # Wedding indexing build (2026-06-12)
    f"https://{HOST}/weddings",
    f"https://{HOST}/services/wedding-photography-sharjah",
    f"https://{HOST}/services/wedding-photography-ajman",
    f"https://{HOST}/services/wedding-photography-ras-al-khaimah",
    f"https://{HOST}/services/wedding-photography-fujairah",
    f"https://{HOST}/services/wedding-photography-umm-al-quwain",
    # English locations
    f"https://{HOST}/locations/dubai",
    f"https://{HOST}/locations/abu-dhabi",
    f"https://{HOST}/locations/sharjah",
    f"https://{HOST}/locations/ajman",
    f"https://{HOST}/locations/ras-al-khaimah",
    f"https://{HOST}/locations/fujairah",
    f"https://{HOST}/locations/umm-al-quwain",
    # Arabic pages
    f"https://{HOST}/ar/",
    f"https://{HOST}/ar/about",
    f"https://{HOST}/ar/services",
    f"https://{HOST}/ar/pricing",
    f"https://{HOST}/ar/contact",
    f"https://{HOST}/ar/blog",
    f"https://{HOST}/ar/testimonials",
    f"https://{HOST}/ar/locations",
    # Chinese pages
    f"https://{HOST}/zh/",
    f"https://{HOST}/zh/about",
    f"https://{HOST}/zh/services",
    f"https://{HOST}/zh/pricing",
    f"https://{HOST}/zh/contact",
    f"https://{HOST}/zh/blog",
    f"https://{HOST}/zh/testimonials",
    f"https://{HOST}/zh/locations",
    # Russian pages
    f"https://{HOST}/ru/",
    f"https://{HOST}/ru/about",
    f"https://{HOST}/ru/services",
    f"https://{HOST}/ru/pricing",
    f"https://{HOST}/ru/contact",
    f"https://{HOST}/ru/blog",
    f"https://{HOST}/ru/testimonials",
    f"https://{HOST}/ru/locations",
    # EN Blog posts — Batch 1
    f"https://{HOST}/blog/best-production-companies-dubai-2026",
    f"https://{HOST}/blog/how-much-does-video-production-cost-dubai-2026",
    f"https://{HOST}/blog/wedding-photographer-cost-dubai-2026",
    f"https://{HOST}/blog/drone-photography-dubai-2026",
    f"https://{HOST}/blog/real-estate-videography-dubai-2026",
    f"https://{HOST}/blog/brand-film-production-dubai-2026",
    f"https://{HOST}/blog/social-media-content-creation-dubai-2026",
    f"https://{HOST}/blog/corporate-photography-dubai-2026",
    f"https://{HOST}/blog/automotive-photography-dubai-2026",
    f"https://{HOST}/blog/hotel-photography-dubai-2026",
    f"https://{HOST}/blog/product-photography-dubai-2026",
    f"https://{HOST}/blog/youtube-video-production-dubai-2026",
    f"https://{HOST}/blog/fashion-photography-dubai-2026",
    # EN Blog posts — Batch 2
    f"https://{HOST}/blog/event-photography-dubai-2026",
    f"https://{HOST}/blog/food-photography-dubai-2026",
    f"https://{HOST}/blog/real-estate-photography-dubai-2026",
    f"https://{HOST}/blog/corporate-video-production-dubai-2026",
    f"https://{HOST}/blog/music-video-production-dubai-2026",
    f"https://{HOST}/blog/company-profile-video-dubai-2026",
    f"https://{HOST}/blog/testimonial-video-dubai-2026",
    f"https://{HOST}/blog/influencer-content-creator-dubai-2026",
    f"https://{HOST}/blog/downtown-dubai-photographer-2026",
    f"https://{HOST}/blog/restaurant-photography-dubai-2026",
    f"https://{HOST}/blog/luxury-lifestyle-photography-dubai-2026",
    f"https://{HOST}/blog/birthday-party-photographer-dubai-2026",
    f"https://{HOST}/blog/abu-dhabi-photographer-2026",
    f"https://{HOST}/blog/filipino-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/sports-photography-dubai-2026",
    f"https://{HOST}/blog/green-screen-studio-dubai-2026",
    # Sub-industry pages (all 23 sub-slugs)
    f"https://{HOST}/industries/automotive/dealership",
    f"https://{HOST}/industries/hospitality/resorts",
    f"https://{HOST}/industries/real-estate/luxury-villa",
    f"https://{HOST}/industries/real-estate/off-plan",
    f"https://{HOST}/industries/fashion/model-portfolio",
    f"https://{HOST}/industries/fashion/fashion-reels",
    f"https://{HOST}/industries/food-beverage/restaurants",
    f"https://{HOST}/industries/food-beverage/menu-photography",
    f"https://{HOST}/industries/sports/football",
    f"https://{HOST}/industries/sports/fitness",
    f"https://{HOST}/industries/corporate/investor-pitch",
    f"https://{HOST}/industries/corporate/annual-report",
    f"https://{HOST}/industries/tech/saas",
    f"https://{HOST}/industries/sports/padel",
    f"https://{HOST}/industries/automotive/car-launch",
    f"https://{HOST}/industries/sports/cycling",
    f"https://{HOST}/industries/sports/running",
    f"https://{HOST}/industries/tech/gitex",
    f"https://{HOST}/industries/tech/startup",
    f"https://{HOST}/industries/tech/fintech",
    f"https://{HOST}/industries/healthcare/dental",
    f"https://{HOST}/industries/corporate/company-profile",
    f"https://{HOST}/industries/hospitality/hotels",
    # EN Blog posts — Batch 3 (photography guides)
    f"https://{HOST}/blog/ecommerce-product-photography-dubai-2026",
    f"https://{HOST}/blog/aerial-videography-dubai-2026",
    f"https://{HOST}/blog/family-photographer-dubai-2026",
    f"https://{HOST}/blog/passport-photo-dubai-2026",
    f"https://{HOST}/blog/corporate-event-videography-dubai-2026",
    f"https://{HOST}/blog/newborn-photographer-dubai-2026",
    f"https://{HOST}/blog/maternity-photographer-dubai-2026",
    f"https://{HOST}/blog/brand-photography-dubai-2026",
    f"https://{HOST}/blog/360-video-production-dubai-2026",
    f"https://{HOST}/blog/graduation-photographer-dubai-2026",
    # RU Blog posts
    f"https://{HOST}/ru/blog/korporativnoe-video-dubai-2026",
    f"https://{HOST}/ru/blog/semka-nedvizhimosti-dubai-2026",
    f"https://{HOST}/ru/blog/svadebnyi-fotograf-dubai-2026",
    f"https://{HOST}/ru/blog/stoimost-videosemki-dubai-2026",
    f"https://{HOST}/ru/blog/rily-socsietey-dubai-2026",
    f"https://{HOST}/ru/blog/fotosyomka-feropriiatiy-dubai-2026",
    f"https://{HOST}/ru/blog/fotografiya-edy-dubai-2026",
    f"https://{HOST}/ru/blog/semeinaya-fotosessiya-dubai-2026",
    f"https://{HOST}/ru/blog/fotograf-novorozhdennykh-dubai-2026",
    # AR Blog posts
    f"https://{HOST}/ar/blog/video-sharikaat-dubai-2026",
    f"https://{HOST}/ar/blog/taswiremolak-dubai-2026",
    f"https://{HOST}/ar/blog/taswirzifaf-dubai-2026",
    f"https://{HOST}/ar/blog/asear-tasswirvideo-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-zifaf-emirati-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-zifaf-arabi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-taaam-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-muatamart-dubai-2026",
    f"https://{HOST}/ar/blog/tasjil-video-faaliyat-dubai-2026",
    f"https://{HOST}/ar/blog/intaj-klip-musiqi-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-khetuba-dubai-2026",
    f"https://{HOST}/ar/blog/taswir-mawaalid-dubai-2026",
    # EN Blog posts — Batch 4 (keyword gap fills, 2026-06-17)
    f"https://{HOST}/blog/portrait-photographer-dubai-2026",
    f"https://{HOST}/blog/reels-videographer-dubai-2026",
    f"https://{HOST}/blog/personal-branding-photographer-dubai-2026",
    f"https://{HOST}/blog/amazon-product-photography-dubai-2026",
    f"https://{HOST}/blog/headshot-photographer-dubai-2026",
    # EN Blog posts — Tier 2 gap fills (2026-06-18)
    f"https://{HOST}/blog/freelance-photographer-dubai-2026",
    f"https://{HOST}/blog/watch-photography-dubai-2026",
    f"https://{HOST}/blog/men-photographer-dubai-2026",
    # EN Blog posts — Sprint 1: Wedding sub-niches (2026-06-18)
    f"https://{HOST}/blog/indian-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/pakistani-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/emirati-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/filipino-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/pre-wedding-shoot-dubai-2026",
    f"https://{HOST}/blog/nigerian-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/russian-wedding-photographer-dubai-2026",
    f"https://{HOST}/blog/luxury-wedding-photographer-dubai-2026",
    # EN Blog posts — Sprint 2: Sports sub-niches (2026-06-18)
    f"https://{HOST}/blog/cricket-photographer-dubai-2026",
    f"https://{HOST}/blog/football-photographer-dubai-2026",
    f"https://{HOST}/blog/tennis-photographer-dubai-2026",
    f"https://{HOST}/blog/golf-photographer-dubai-2026",
    f"https://{HOST}/blog/fitness-photographer-dubai-2026",
    f"https://{HOST}/blog/gym-photography-dubai-2026",
    f"https://{HOST}/blog/marathon-photographer-dubai-2026",
    f"https://{HOST}/blog/motorsport-photographer-dubai-2026",
]

payload = {
    "host": HOST,
    "key": API_KEY,
    "keyLocation": KEY_LOCATION,
    "urlList": URLS,
}

req = urllib.request.Request(
    "https://api.indexnow.org/indexnow",
    data=json.dumps(payload).encode("utf-8"),
    headers={"Content-Type": "application/json; charset=utf-8"},
    method="POST",
)

with urllib.request.urlopen(req) as resp:
    print(f"Status: {resp.status}")
    print(f"URLs submitted: {len(URLS)}")
    print("Done.")
