// Auto-generated by scripts/consolidate.mjs — do not edit by hand.
// Blog slugs that now 301 elsewhere. The sitemap must not list them: a sitemap full
// of redirects wastes crawl budget and tells Google the file is stale.
export const RETIRED_BLOG_SLUGS = new Set<string>([
  "tvc-production-uae-tv-commercial-costs-process-guide-2026",
  "music-video-production-uae-pricing-process-guide-2026",
  "best-video-production-company-in-dubai-for-corporate-video-2026-guide-2026",
  "product-video-production-uae-pricing-process-guide-2026",
  "video-podcast-production-dubai-uae-setup-pricing-full-guide-2026-2026",
  "sports-production-company-in-the-uae-football-cricket-basketball-fight-night-coverage-2026-2026",
  "sports-broadcast-production-uae-full-match-coverage-from-aed-25-000-2026-2026",
  "car-commercial-production-studio-in-the-uae-full-capability-guide-2026-2026",
  "headshot-photography-dubai-2026",
  "business-headshots-dubai-2026",
  "baby-photographer-dubai-2026",
  "maternity-photography-dubai-2026",
  "pregnancy-photoshoot-dubai-2026",
  "kids-photography-dubai-2026",
  "birthday-party-photographer-dubai-2026",
  "car-photography-dubai-2026",
  "indian-wedding-photography-dubai",
  "indian-wedding-photography-dubai-2026",
  "social-media-content-creation-dubai-2026",
  "best-social-media-content-creators-dubai-2026",
  "commercial-production-dubai-2026",
  "drone-photography-dubai-2026",
  // ── MANUAL ADDITIONS — do not remove ──────────────────────────────────────
  // These two are RENAME TARGETS of scripts/consolidate.mjs (the long malformed
  // post slugs re-map to them), which is why the generator never adds them to
  // this set: from consolidate.mjs's point of view they are survivors. They are
  // NOT standalone articles — both permanently redirect to
  // /services/live-streaming (next.config.mjs) — so the sitemap must not list
  // them. Adding them here is a manual override of the generator's survivor
  // classification, kept in comments so a regeneration cannot silently drop it.
  "sports-production-company-uae-2026",
  "sports-broadcast-production-uae-2026",
]);
